# Generated by Django 3.2.23 on 2023-11-13 10:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Address',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address_id', models.CharField(max_length=2)),
                ('street_address', models.CharField(max_length=255)),
                ('city', models.CharField(max_length=255)),
                ('country', models.CharField(max_length=255)),
                ('state_province', models.CharField(max_length=255)),
                ('postal_zip_code', models.CharField(max_length=9)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='payment.customer')),
            ],
        ),
    ]
